#!/bin/bash
# Weather_CLI Version 0.1 by AptGetMe 2024

# define version
_version="0.1"

# define global colors
_yellow_BOLD_FG="\033[1;38;5;226m"
_orange_BOLD_FG="\033[1;38;5;214m"
_grey_BOLD_FG="\033[1;38;5;248m"
_white_BOLD_FG="\033[1;38;5;255m"
_green_BOLD_FG="\033[1;38;5;42m"

_sky1_BG="\033[48;5;105m"
_sky2_BG="\033[48;5;69m"
_sky3_BG="\033[48;5;33m"
_sky4_BG="\033[48;5;21m"

_colorEnd="\033[m"

# global array to hold final output to screen
_out=()

function sunny()
{                                                        
  _out=("$_yellow_BOLD_FG               ++               $_colorEnd"
        "$_yellow_BOLD_FG       ++     ++++     ++       $_colorEnd"
        "$_yellow_BOLD_FG       +++++ ++++++ +++++       $_colorEnd"
        "$_yellow_BOLD_FG        +++++      +++++        $_colorEnd"
        "$_yellow_BOLD_FG        ++$_orange_BOLD_FG  ;;;;;;;;$_yellow_BOLD_FG  ++        $_colorEnd"
        "$_yellow_BOLD_FG  +++++++$_orange_BOLD_FG ;;;;;;;;;;;;$_yellow_BOLD_FG +++++++  $_colorEnd"
        "$_yellow_BOLD_FG    ++++$_orange_BOLD_FG ;;;;;;;;;;;;;;$_yellow_BOLD_FG ++++    $_colorEnd"
        "$_yellow_BOLD_FG      ++$_orange_BOLD_FG ;;;;;;;;;;;;;;$_yellow_BOLD_FG ++      $_colorEnd"
        "$_yellow_BOLD_FG    ++++$_orange_BOLD_FG ;;;;;;;;;;;;;;$_yellow_BOLD_FG ++++    $_colorEnd"
        "$_yellow_BOLD_FG  +++++++$_orange_BOLD_FG ;;;;;;;;;;;;$_yellow_BOLD_FG +++++++  $_colorEnd"
        "$_yellow_BOLD_FG        ++$_orange_BOLD_FG  ;;;;;;;;$_yellow_BOLD_FG  ++        $_colorEnd"
        "$_yellow_BOLD_FG        +++++      +++++        $_colorEnd"
        "$_yellow_BOLD_FG       +++++ ++++++ +++++       $_colorEnd"
        "$_yellow_BOLD_FG       ++     ++++     ++       $_colorEnd"
        "$_yellow_BOLD_FG               ++               $_colorEnd")
}
function partly_sunny()
{                            
  _out=("$_yellow_BOLD_FG               ++               $_colorEnd"
        "$_yellow_BOLD_FG       ++     ++++     ++       $_colorEnd"
        "$_yellow_BOLD_FG       +++++ ++++++ +++++       $_colorEnd"
        "$_yellow_BOLD_FG        +++++      ++++++       $_colorEnd"
        "$_yellow_BOLD_FG        ++$_orange_BOLD_FG  ;;;;;;;;;$_yellow_BOLD_FG ++        $_colorEnd"
        "$_yellow_BOLD_FG  +++++++$_orange_BOLD_FG ;;;;;;;;;;;;$_yellow_BOLD_FG +++++++  $_colorEnd"
        "$_yellow_BOLD_FG    ++++$_orange_BOLD_FG ;;;;;;;;;;;;;;$_yellow_BOLD_FG ++++    $_colorEnd"
        "$_yellow_BOLD_FG      ++$_orange_BOLD_FG ;;;;;;;;;;;;;;$_yellow_BOLD_FG ++      $_colorEnd"
        "$_yellow_BOLD_FG    ++++$_orange_BOLD_FG ;;;;;;;;;;;;;;$_yellow_BOLD_FG ++++    $_colorEnd"
        "$_yellow_BOLD_FG  +++++++$_orange_BOLD_FG ;;;;;;;;;;;;$_yellow_BOLD_FG +++++++  $_colorEnd"
        "$_grey_BOLD_FG     ++$_white_BOLD_FG....$_grey_BOLD_FG++$_orange_BOLD_FG;;;;;;;$_yellow_BOLD_FG  ++        $_colorEnd"
        "$_grey_BOLD_FG   ++$_white_BOLD_FG........$_grey_BOLD_FG+;++$_yellow_BOLD_FG+ ++++++       $_colorEnd"
        "$_grey_BOLD_FG +++;$_white_BOLD_FG............$_grey_BOLD_FG++$_yellow_BOLD_FG +++++       $_colorEnd"
        "$_grey_BOLD_FG +$_white_BOLD_FG...............$_grey_BOLD_FG:+$_yellow_BOLD_FG    ++       $_colorEnd"
        "$_grey_BOLD_FG +;$_white_BOLD_FG.............$_grey_BOLD_FG:+              $_colorEnd"
        "$_grey_BOLD_FG   +++++++++++++                $_colorEnd")
}

# get current date with "date" cmd and store in variable
_fullDate=$(date '+%A %B %d, %Y')
echo "Gathering todays weather report $_fullDate"

# create tmp file and setup clean up on exit
_tmpFile=$(mktemp)
trap 'rm -f $_tmpFile' EXIT

# start "inxi" cmd in background to get weather
# pipe output to tee command to write to tmp file
# remove stdout 
inxi -xxxw --force colors | tee "$_tmpFile" >/dev/null &

# save PID and setup kill signal handling
_inxiPID=$!
trap 'kill $_inxiPID' SIGINT
echo "Starting inxi weather process $_inxiPID"

# turn cursor shape to steady underline
echo -ne "\e[4 q"

# while waiting for inxi cmd to exit, play ASCII animation
while ps -p $_inxiPID >/dev/null;
do
    echo -en "$_green_BOLD_FG-\b"
    sleep 0.1
    echo -en "\\\\\b"
    sleep 0.1
    echo -en "|\b"
    sleep 0.1
    echo -en "/\b"
    sleep 0.1
    echo -en "-\b"
    sleep 0.1
    echo -en "\\\\\b"
    sleep 0.1
    echo -en "|\b"
    sleep 0.1
    echo -en "/\b"
    sleep 0.1
    echo -en "-\b"
    sleep 0.1
    echo -en "*$_colorEnd"
done
# restore cursor shape back to default
echo -ne "\e[0 q"

clear
echo -e "  $_green_BOLD_FG----------------------------------------------------------"
echo -e "  |                        Finished                        |"
echo -e "  ----------------------------------------------------------$_colorEnd\n"

# read inxi weather results from tmpFile, deliminate on spaces
mapfile -d ' ' _inxiRaw < "$_tmpFile"

# remove extra whitespaces and newlines
_inxiPretty=()
for _i in "${_inxiRaw[@]}"
do
    _line="$(echo "$_i" | xargs)"
    if [[ $_line != "" ]]; then
        _inxiPretty+=("$_line")
    fi
done

# debug code to see array of weather output
#for _i in "${!_inxiPretty[@]}"
#do
#    echo "$_i ${_inxiPretty[_i]}"
#done

# test out ASCII art for weather results
sunny

# test out formating the final results
echo -e "${_out[0]}    ${_inxiPretty[0]} ${_inxiPretty[1]}"
echo -e "${_out[1]}    ${_inxiPretty[2]} ${_inxiPretty[5]} ${_inxiPretty[6]}"
echo -e "${_out[2]}    ${_inxiPretty[7]} ${_inxiPretty[8]} ${_inxiPretty[9]}"
echo -e "${_out[3]}    ${_inxiPretty[10]} ${_inxiPretty[11]} ${_inxiPretty[12]} ${_inxiPretty[13]} ${_inxiPretty[18]} ${_inxiPretty[19]}"
echo -e "${_out[4]}    ${_inxiPretty[20]} ${_inxiPretty[21]} ${_inxiPretty[22]}"
echo -e "${_out[5]}    ${_inxiPretty[23]} ${_inxiPretty[24]}"
echo -e "${_out[6]}    ${_inxiPretty[25]} ${_inxiPretty[28]} ${_inxiPretty[29]}"
echo -e "${_out[7]}    ${_inxiPretty[30]} ${_inxiPretty[31]} ${_inxiPretty[32]} ${_inxiPretty[33]}"
echo -e "${_out[8]}    ${_inxiPretty[45]} ${_inxiPretty[46]} ${_inxiPretty[47]} ${_inxiPretty[48]} ${_inxiPretty[49]} ${_inxiPretty[50]}"
echo -e "${_out[9]}    ${_inxiPretty[54]} ${_inxiPretty[55]}"
echo -e "${_out[10]}    ${_inxiPretty[56]} ${_inxiPretty[57]}"
echo -e "${_out[11]}    ${_inxiPretty[58]} ${_inxiPretty[59]}"
echo -e "${_out[12]}"
echo -e "${_out[13]}"
echo -e "${_out[14]}"
echo -e "${_out[15]}"
